# Generated by Django 4.2.16 on 2025-01-23 17:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('is_defective', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('remarks', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('waiting_sparepart', 'Waiting Sparepart'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='accessible_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True, verbose_name='Subject')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('properties', models.ManyToManyField(blank=True, related_name='user_profiles', to='myappLubd.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('room_type', models.CharField(db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('properties', models.ManyToManyField(blank=True, related_name='rooms', to='myappLubd.property')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Uploaded image file', null=True, upload_to='maintenance_job_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the image was uploaded')),
                ('job', models.ForeignKey(help_text='The job associated with this image', on_delete=django.db.models.deletion.CASCADE, related_name='job_images', to='myappLubd.job')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_job_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Image',
                'verbose_name_plural': 'Job Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='myappLubd.jobimage'),
        ),
        migrations.AddField(
            model_name='job',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='myappLubd.room'),
        ),
        migrations.AddField(
            model_name='job',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='myappLubd.topic'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='myappLubd_r_room_ty_90b2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='myappLubd_r_is_acti_767b23_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='myappLubd_j_status_4362b5_idx'),
        ),
    ]
